### PR TITLE
Removed Christmas Island since it shares code with australia https://…

### PR DESCRIPTION
**Pull request by AdGalesso**
…en.wikipedia.org/wiki/Telephone_numbers_in_Christmas_Island

### CODE REVIEW

**Comment by nikhiln** [comment]
@AdGalesso I think I added Christmas_Island based on suggestion earlier. Are we sure that it's no longer needed?

**Comment by AdGalesso** [comment]
Yes, Christmas Island is an Australian territory in the Indian Ocean

**Comment by jrlumbang** [comment]
@nikhiln Can we merge this change already? :)

**Comment by AdGalesso** [comment]
Hey @nikhiln, sorry to bother, did you package a new version to NPM?

**Comment by nikhiln** [comment]
@AdGalesso Sorry didn't get chance last week. I'll try to do this week.

**Comment by AdGalesso** [comment]
Is there something I can help?

**Comment by nikhiln** [comment]
@AdGalesso Published new version.

**Pull request merged**
